### ISSUE TITLE
captures screen on all steps even after disabling it with  -Dtimeline=false 

### ISSUE THREAD

**Issue by amit-decathlon** [testvagrant/Ekam-Template#2]
**Describe the bug**
cmd parameter -Dtimeline=false is not working

By default the parameter is set to true. 
By which on every test step - @MobileStep/ @WebStep captures screenshot for Allure report

When it is disabled explicitly using -Dtimeline=false in cmd line argument, still it is capturing the screenshot.

**To Reproduce**
Run mobile tests using gradle task. example : 
./gradlew runMobileTests -Dtags=SANITY -Dtimeline=false

**Expected behavior**
When checked in Allure report, The screenshots should not be captured for all the MobileSteps/ WebSteps. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Vivo Y91 - 1951
 - OS: Android 11.0
 - Browser : Native app
 - Version : 

**Additional context**
Refer comms : 
https://testvagrant.slack.com/archives/C026UFB5G93/p1642660877015800

**Comment by Prajwalgn-07** [comment]
It's not a bug, kindly provide the `timeline:System.getProperty("timeline", "false")` in **build.gradle**->**_systemProperties_**

**Comment by amit-decathlon** [comment]
This is tested and works as expected : 
Default - true - captures screen on all steps
config - false - takes screenshot only on failure steps
