### ISSUE TITLE
Ability to set values in desired capabilities json and browser stack json via env variable

### ISSUE THREAD

**Issue by radhakrishnan-mohan** [testvagrant/Ekam-Template#7]
**Is your feature request related to a problem? Please describe.**
1. Currently, we have to enter credentials of browser stack in codebase which is not considered a good practice. We should ideally be able to pass it via env variables from CI job where it can be masked. 
2. In browser stack, we need to upload the app and use the app url in desired capabilities. Same is applicable if we are using other apps which needs to be installed for the app under test to work. The other apps also needs to be passed as app url in desired capability. Since the app url can change based on each build we need a way in which it can be passed as env variables
**Describe the solution you'd like**
Solution similar to how we are passing env variable on hosts.json

**Describe alternatives you've considered**
Have not considered any alternatives
**Additional context**

**Comment by Prajwalgn-07** [comment]
@radhakrishnan-mohan for the first one we have already
**Reference:**[ekam](https://docs.ekam.studio/docs/web_automation/executing_tests-_in_cloud/browserstack/#:~:text=Use%20this%20syntax%20%22%24%7Benv%3A%20%3Carg%20name%3E%7D%22%20for%20the%20required%20fields%20in%20the%20browserstack.json%20file%2C%20provided%20an%20example%20below)

**Comment by radhakrishnan-mohan** [comment]
@Prajwalgn-07 This should work for first part. Thanks

**Comment by Prajwalgn-07** [comment]
@radhakrishnan-mohan For the second part, I think u can apply the same logic has done in the [first part]( https://docs.ekam.studio/docs/web_automation/executing_tests-_in_cloud/browserstack/#:~:text=Use%20this%20syntax%20%22%24%7Benv%3A%20%3Carg%20name%3E%7D%22%20for%20the%20required%20fields%20in%20the%20browserstack.json%20file%2C%20provided%20an%20example%20below)and create env variable for app URL in the desired capabilities, can u check once and update

**Comment by Prajwalgn-07** [comment]
@radhakrishnan-mohan update **ekam->1.0.2** and check it
